import { RentalRequest, RentalRequestTab } from "@/types/rental-request";

export const mockRentalRequests: RentalRequest[] = [
  {
    id: "req-001",
    propertyId: "prop-001",
    propertyTitle: "Căn hộ cao cấp Landmark 81",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "A101",
    requesterName: "Nguyễn Văn An",
    requesterPhone: "0901234567",
    requesterEmail: "nguyenvanan@email.com",
    requestDate: "2024-01-15",
    moveInDate: "2024-02-01",
    status: "sent",
    notes: "Tôi muốn thuê căn hộ này cho gia đình",
    bedrooms: 2,
    bathrooms: 2,
    area: 75,
    address: "Quận 1, TP Hồ Chí Minh",
    furnitureStatus: "Đầy đủ",
    category: "Căn hộ",
    price: 15000000,
    contractDuration: 12,
    deposit: 30000000,
    monthlyRent: 15000000,
  },
  {
    id: "req-002",
    propertyId: "prop-002",
    propertyTitle: "Phòng trọ gần ĐH Bách Khoa",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "B205",
    requesterName: "Trần Thị Bình",
    requesterPhone: "0987654321",
    requesterEmail: "tranthibinh@email.com",
    requestDate: "2024-01-10",
    moveInDate: "2024-01-25",
    status: "pending",
    notes: "Sinh viên năm 3, cần phòng yên tĩnh để học tập",
    bedrooms: 1,
    bathrooms: 1,
    area: 25,
    address: "Quận 3, TP Hồ Chí Minh",
    furnitureStatus: "Cơ bản",
    category: "Phòng trọ",
    price: 3500000,
    contractDuration: 6,
    deposit: 7000000,
    monthlyRent: 3500000,
  },
  {
    id: "req-003",
    propertyId: "prop-003",
    propertyTitle: "Studio hiện đại Q7",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "C301",
    requesterName: "Lê Minh Cường",
    requesterPhone: "0912345678",
    requesterEmail: "leminhcuong@email.com",
    requestDate: "2024-01-12",
    moveInDate: "2024-02-15",
    status: "approved",
    notes: "Làm việc remote, cần không gian thoáng đãng",
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    address: "Quận 7, TP Hồ Chí Minh",
    furnitureStatus: "Đầy đủ",
    category: "Studio",
    price: 8000000,
    contractDuration: 12,
    deposit: 16000000,
    monthlyRent: 8000000,
  },
  {
    id: "req-004",
    propertyId: "prop-004",
    propertyTitle: "Nhà nguyên căn Thủ Đức",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "D01",
    requesterName: "Phạm Văn Đức",
    requesterPhone: "0945678901",
    requesterEmail: "phamvanduc@email.com",
    requestDate: "2024-01-08",
    moveInDate: "2024-01-20",
    status: "rejected",
    notes: "Gia đình 4 người, cần nhà rộng",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    address: "Thủ Đức, TP Hồ Chí Minh",
    furnitureStatus: "Trống",
    category: "Nhà nguyên căn",
    price: 20000000,
    contractDuration: 24,
    deposit: 40000000,
    monthlyRent: 20000000,
    rejectionReason: "Không đáp ứng yêu cầu tài chính",
  },
  {
    id: "req-005",
    propertyId: "prop-005",
    propertyTitle: "Căn hộ Vinhomes Central Park",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "E1205",
    requesterName: "Hoàng Thị Mai",
    requesterPhone: "0967890123",
    requesterEmail: "hoangthimai@email.com",
    requestDate: "2024-01-20",
    moveInDate: "2024-03-01",
    status: "rejected",
    notes: "Đã được duyệt, đang chờ thanh toán",
    bedrooms: 2,
    bathrooms: 2,
    area: 85,
    address: "Quận Bình Thạnh, TP Hồ Chí Minh",
    furnitureStatus: "Đầy đủ",
    category: "Căn hộ",
    price: 25000000,
    contractDuration: 12,
    deposit: 50000000,
    monthlyRent: 25000000,
  },
  {
    id: "req-006",
    propertyId: "prop-006",
    propertyTitle: "Phòng trọ cao cấp Q1",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "F401",
    requesterName: "Võ Thanh Tùng",
    requesterPhone: "0934567890",
    requesterEmail: "vothanhtung@email.com",
    requestDate: "2024-01-18",
    moveInDate: "2024-02-10",
    status: "sent",
    notes: "Nhân viên văn phòng, cần gần trung tâm",
    bedrooms: 1,
    bathrooms: 1,
    area: 30,
    address: "Quận 1, TP Hồ Chí Minh",
    furnitureStatus: "Đầy đủ",
    category: "Phòng trọ",
    price: 6000000,
    contractDuration: 6,
    deposit: 12000000,
    monthlyRent: 6000000,
  },
  {
    id: "req-007",
    propertyId: "prop-007",
    propertyTitle: "Căn hộ dịch vụ Q3",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "G502",
    requesterName: "Đặng Thị Lan",
    requesterPhone: "0956789012",
    requesterEmail: "dangthilan@email.com",
    requestDate: "2024-01-14",
    moveInDate: "2024-01-28",
    status: "pending",
    notes: "Cần thuê ngắn hạn 3 tháng",
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    address: "Quận 3, TP Hồ Chí Minh",
    furnitureStatus: "Đầy đủ",
    category: "Căn hộ",
    price: 12000000,
    contractDuration: 3,
    deposit: 24000000,
    monthlyRent: 12000000,
  },
  {
    id: "req-008",
    propertyId: "prop-008",
    propertyTitle: "Studio The Sun Avenue",
    propertyImage: "/public/assets/imgs/house-item.png",
    roomCode: "H203",
    requesterName: "Bùi Văn Hùng",
    requesterPhone: "0923456789",
    requesterEmail: "buivanhung@email.com",
    requestDate: "2024-01-16",
    moveInDate: "2024-02-05",
    status: "rejected",
    notes: "Freelancer, làm việc tại nhà",
    bedrooms: 1,
    bathrooms: 1,
    area: 32,
    address: "Quận 2, TP Hồ Chí Minh",
    furnitureStatus: "Cơ bản",
    category: "Studio",
    price: 9000000,
    contractDuration: 12,
    deposit: 18000000,
    monthlyRent: 9000000,
    rejectionReason: "Đã có người thuê khác",
  },
];

export const rentalRequestTabs: RentalRequestTab[] = [
  { id: "all", label: "Tất cả", count: mockRentalRequests.length },
  {
    id: "sent",
    label: "Đã gửi",
    count: mockRentalRequests.filter((r) => r.status === "sent").length,
  },
  {
    id: "pending",
    label: "Chờ đồng ý",
    count: mockRentalRequests.filter((r) => r.status === "pending").length,
  },
  {
    id: "rejected",
    label: "Từ chối",
    count: mockRentalRequests.filter((r) => r.status === "rejected").length,
  },
  {
    id: "awaiting-payment",
    label: "Chờ thanh toán",
    count: mockRentalRequests.filter((r) => r.status === "awaiting-payment")
      .length,
  },
];
